export const TOGGLE_FILTER = 'TOGGLE_FILTER_MODAL';
export const TOGGLE_SEARCH = 'TOGGLE_SEARCH';

export const SHOW_LOCATION_HISTORY = 'SHOW_LOCATION_HISTORY';
export const HIDE_LOCATION_HISTORY = 'HIDE_LOCATION_HISTORY';

export const SHOW_CATEGORIES = 'SHOW_CATEGORIES';
export const HIDE_CATEGORIES = 'HIDE_CATEGORIES';
